### ISSUE TITLE
mv: target ~/.cache/fisher/github.com/... is not a directory

### ISSUE THREAD

**Issue by tobia** [jorgebucaran/fisher#557] opened 2019-11-06 11:46 UTC
I cannot seem to be able to install new packages using any 3.2.x version of fisher.

Here is an example using 3.2.0, but the same error occurs with any later version including master:

```
▶ curl -sSo ~/.config/fish/functions/fisher.fish https://raw.githubusercontent.com/jorgebucaran/fisher/3.2.0/fisher.fish
▶ source ~/.config/fish/functions/fisher.fish
▶ rm -r ~/.config/fisher/ ~/.cache/fisher/ ~/.config/fish/fishfile
▶ fisher add reitzig/sdkman-for-fish@v1.3.0
created empty fishfile in ~/.config/fish/fishfile
fetching https://codeload.github.com/reitzig/sdkman-for-fish/tar.gz/v1.3.0
mv: target '/home/tobia/.cache/fisher/github.com/reitzig/sdkman-for-fish' is not a directory
cp: cannot stat '/home/tobia/.cache/fisher/github.com/reitzig/sdkman-for-fish': No such file or directory
done in 0.50s
```

Here is the same command with 3.1.1, which works properly:

```
▶ curl -sSo ~/.config/fish/functions/fisher.fish https://raw.githubusercontent.com/jorgebucaran/fisher/3.1.1/fisher.fish
▶ source ~/.config/fish/functions/fisher.fish
▶ rm -r ~/.config/fisher/ ~/.cache/fisher/ ~/.config/fish/fishfile
▶ fisher add reitzig/sdkman-for-fish@v1.3.0
created empty fishfile in ~/.config/fish/fishfile
fetching https://codeload.github.com/reitzig/sdkman-for-fish/tar.gz/v1.3.0
linking ~/.config/fish/functions/sdk.fish
linking ~/.config/fish/completions/sdk.fish
linking ~/.config/fish/conf.d/sdk.fish
added 1 package in 0.61s
```

I'm using fish 2.7.1, installed from the default apt repository of Ubuntu 18.04

**Comment by jorgebucaran** [comment] 2019-11-06 12:24
@tobia Did you upgrade from 3.1.1 to 3.2.0 while using fish 2.7.1 just now? I'd like to know if the problem was fish 2.7.1 or a breaking change that I might have sneaked into the code.

**Comment by tobia** [comment] 2019-11-06 12:40
Yes, I'm using fish 2.7.1 and I tried several versions of fisher, resetting all caches in between, as you can see from the logs I posted.

Either I have something weird in my system, or there was a breaking change in 3.20.

**Comment by jorgebucaran** [comment] 2019-11-06 12:57
@tobia Can you try removing fisher completely and trying again?

**Comment by tobia** [comment] 2019-11-06 13:14
I've been removing `~/.config/fisher/`, `~/.cache/fisher/`, `~/.config/fish/fishfile`, and replacing `~/.config/fish/functions/fisher.fish`.

What else should I remove?

**Comment by jorgebucaran** [comment] 2019-11-06 13:37
I mean just run `fisher self-uninstall`. But it seems that this might not the problem, but something in your system, but I have no idea what! 🤔

**Comment by j2ghz** [comment] 2020-03-27 13:21
I was getting the same issue in WSL. While gathering facts to report the issue, I found https://unix.stackexchange.com/a/352854.
I checked, and after closing VS Code (in which I had the `~` folder open) it worked.

**Comment by jorgebucaran** [comment] 2020-03-27 15:02
@tobia Any luck?

**Comment by MaSven** [comment] 2020-05-04 21:07
I have the same problem with fish version 3.1.0. I tried it with fisher self-uninstall and after that installed it again but no luck

**Comment by MaSven** [comment] 2020-05-04 21:36
After debuggin the script, i found out, that at line 306 the pkgname is missing.
So the command
`command mkdir -p $fisher_config/$pkg $fisher_cache/(command dirname $pkg)`
Does create 
> ~/.config/fisher/github.com/reitzig/sdkman-for-fish 
and
> ~/.cache/fisher/github.com/reitzig
So the second one is missing the subdir sdkman-for-fish

**Comment by MaSven** [comment] 2020-05-04 21:46
Ok no this is not the problem the same happens with 
`fisher add jethrokuan/z`

**Comment by jorgebucaran** [comment] 2020-05-05 01:19
@tobia @MaSven Try to reproduce the problem inside a docker container and share it with me. That's the only way I can imagine debugging this. Needless to say, I've been unable to reproduce this issue.

**Comment by jorgebucaran** [comment] 2020-05-22 16:48
@MaSven @tobia Can you repro in 3.2.11?

**Comment by jorgebucaran** [comment] 2020-05-23 02:51
> @MaSven https://github.com/jorgebucaran/fisher/issues/557#issuecomment-623720880

Maybe `dirname` is not available in your system? What are you using?

**Comment by MaSven** [comment] 2020-05-23 20:31
I tried to recreate it in docker but can't. 
I'am using opensuse TW. I tryed to recreate it with this docker container https://hub.docker.com/r/opensuse/tumbleweed. I will try the new version.

**Comment by MaSven** [comment] 2020-05-23 20:43
Does not work with new version. I get the same error.

**Comment by tobia** [comment] 2020-05-23 20:51
Same here. I'm using a freshly installed Ubuntu 20.04 with the provided Fish 3.1.0 and I get the same error as before:

```
$ curl -sSo ~/.config/fish/functions/fisher.fish https://raw.githubusercontent.com/jorgebucaran/fisher/3.2.11/fisher.fish
$ source ~/.config/fish/functions/fisher.fish
$ rm -r ~/.config/fisher/ ~/.cache/fisher/ ~/.config/fish/fishfile
$ fisher add reitzig/sdkman-for-fish@v1.3.0
created new fishfile in ~/.config/fish/fishfile
fetching https://codeload.github.com/reitzig/sdkman-for-fish/tar.gz/v1.3.0
mv: target '/home/tobia/.cache/fisher/github.com/reitzig/sdkman-for-fish' is not a directory
cp: cannot stat '/home/tobia/.cache/fisher/github.com/reitzig/sdkman-for-fish': No such file or directory
done in 0.46s
```

The 4 lines of code I'm running to test it, as I did in the OP, are: 1. downloading the specific version of fisher; 2. sourcing it into the running shell; 3. removing all fisher-related configurations and caches; 4. trying to add a package.

**Comment by jorgebucaran** [comment] 2020-05-24 04:24
@tobia @MaSven What's the content of your XDG_CONFIG_HOME and XDG_CACHE_HOME env variables?

**Comment by MaSven** [comment] 2020-05-24 07:33
These two environment variables don't exists. 
```
❰sven❙~❱✔≻ echo $XDG_CONFIG_HOME

❰sven❙~❱✔≻ echo $XDG_CACHE_HOME

❰sven❙~❱✔≻ 
```

**Comment by jorgebucaran** [comment] 2020-05-24 07:42
@MaSven  Does your `mkdir` support the `-p` flag (to create intermediate directories as required)?

**Comment by MaSven** [comment] 2020-05-24 07:44
Yes it does 
```fish
❰sven❙~❱✘≻ mkdir --help
Aufruf: mkdir [OPTION]... VERZEICHNIS...
Erzeugen der/des Verzeichnisse(s), wenn sie noch nicht existieren.

Erforderliche Argumente für lange Optionen sind auch für kurze erforderlich.
  -m, --mode=MODUS  Zugriffsrechte setzen (wie bei chmod), nicht a=rwx − umask
  -p, --parents     kein Fehler, wenn vorhanden; übergeordnete
                      Verzeichnisse erzeugen, wenn notwendig
  -v, --verbose     für jedes angelegte Verzeichnis eine Meldung ausgeben
  -Z                   SELinux-Sicherheitskontext jedes erzeugten Verzeichnisses
                         auf den Standardtyp setzen
      --context[=KTXT] wie -Z, oder, wenn angegeben den SELinux- oder SMACK-
                         Kontext auf KTXT setzen
      --help     diese Hilfe anzeigen und beenden
      --version  Versionsinformation anzeigen und beenden

Onlinehilfe für GNU coreutils: <https://www.gnu.org/software/coreutils/>
Melden Sie Übersetzungsfehler für %s an <translation-team-de@lists.sourceforge.net>
Die vollständige Dokumentation ist hier: <https://www.gnu.org/software/coreutils/mkdir>
oder auch lokal mittels „info '(coreutils) mkdir invocation'“
❰sven❙~❱✔≻ 
```

**Comment by jorgebucaran** [comment] 2020-05-24 07:55
> @tobia https://github.com/jorgebucaran/fisher/issues/557#issuecomment-633137889

Here you described the steps to reproduce the bug by installing `reitzig/sdkman-for-fish@v1.3.0`, but could you do the same for a package known to work:

For example repeat your steps, but instead of `reitzig/sdkman-for-fish@v1.3.0` try. Does the problem persist?

```console
$ fisher add jorgebucaran/fish-spark
```


---


> @MaSven https://github.com/jorgebucaran/fisher/issues/557#issuecomment-623720880

Thank you for attempting to debug the script, but I don't think that's not the issue, as our goal there is just to create the parent directory tree of the package. Moving the actual package there occurs later. 

@MaSven What about your `cp` command? Does it support `-f` and `-R`?

**Comment by MaSven** [comment] 2020-05-24 09:33
```fish
❰sven❙~❱✘≻ fisher add jorgebucaran/fish-spark
fetching https://codeload.github.com/jorgebucaran/fish-spark/tar.gz/master
linking ~/.config/fish/functions/spark.fish
added 1 package, removed 1 package in 0.56s
```
This worked.
cp command
```fish
❰sven❙~❱✔≻ cp --help                                                                                                                   
Aufruf: cp [OPTION]... [-T] QUELLE ZIEL                                                                                                
  oder: cp [OPTION]... QUELLE... VERZEICHNIS                                                                                           
  oder: cp [OPTION]... -t VERZEICHNIS QUELLE...                                                                                        
Kopieren von QUELLE nach ZIEL, oder mehreren QUELLE(n) in VERZEICHNIS      
                                                                                                                                       
Erforderliche Argumente für lange Optionen sind auch für kurze erforderlich.
  -a, --archive               genau wie -dpR --preserve=all                                                                            
      --attributes-only       nicht die Dateidaten, sondern nur die Attribute
                                kopieren                                                                                               
      --backup[=KONTROLLE]    eine Sicherung existierender Zieldateien erzeugen                                                        
  -b                          wie --backup, akzeptiert aber kein Argument
      --copy-contents         wenn rekursiv, Inhalt von Spezialdateien kopieren                                                        
  -d                          genau wie --no-dereference --preserve=links                                                              
  -f, --force                 wenn existierende Zieldatei nicht geöffnet werden
                                kann, löschen und erneut versuchen (wird bei    
                                Verwendung der Option -n ignoriert) 
  -i, --interactive           vor einem Überschreiben nachfragen (überstimmt                                                           
                                eine vorangehende Option -n)                                                                           
  -H                          symbolischen Verknüpfungen, die auf der         
                                Kommandozeile als QUELLE angegeben sind,                                                               
                                folgen                                                                                                 
  -l, --link                  Dateien verknüpfen, statt sie zu kopieren 
  -L, --dereference           symbolischen Verknüpfungen in QUELLE immer folgen    
  -n, --no-clobber            keine existierenden Dateien überschreiben             
                                (übersteuert eine vorangehende Option -i)                                                              
  -P, --no-dereference        symbolischen Verknüpfungen in QUELLE nie folgen
  -p                          genau wie --preserve=mode,ownership,timestamps
      --preserve[=ATTR_LIST]  angegebene Datei‐Attribute erhalten wenn möglich
                                (Voreinstellung: mode,ownership,timestamps;
                                weitere Attribute: context, links, xattr, all)
      --no-preserve=ATTR_LIST  Angegebene Attribute nicht erhalten
      --parents                kompletten Quell‐Pfad an VERZEICHNIS anhängen
  -R, -r, --recursive         Verzeichnisse rekursiv kopieren
      --reflink[=WANN]        Klon/CoW Kopien kontrollieren. Siehe unten
      --remove-destination    jede Zieldatei vor dem Versuch, sie zu öffnen,
                                löschen (im Gegensatz zu --force)
      --sparse=WANN           Erstellung von Dateien mit Löchern (s. u.) steuern
      --strip-trailing-slashes  Schrägstriche vom Ende jedes QUELLE‐Arguments
                                entfernen
  -s, --symbolic-link         symbolische Verknüpfungen erzeugen anstatt
                                zu kopieren
  -S, --suffix=ENDUNG         Standard-Sicherungs‐Dateiendung ändern
  -t, --target-directory=VERZ  alle QUELLE‐Argumente in VERZ kopieren
  -T, --no-target-directory   ZIEL als normale Datei behandeln
  -u, --update                nur kopieren, wenn die QUELL‐Datei neuer ist
                                als die Zieldatei oder die Zieldatei nicht
                                existiert
  -v, --verbose               durchgeführte Tätigkeiten erklären
  -x, --one-file-system       in diesem Dateisystem verbleiben
  -Z                           den SELinux-Sicherheitskontext der Zieldatei
                                 auf den Standardtyp setzen
      --context[=KTXT]         Wie -Z, oder, wenn KTXT angegeben wurde, den
                                 SELinux- oder SMACK-Sicherheitskontext auf
                                 KTXT setzen
      --help     diese Hilfe anzeigen und beenden
      --version  Versionsinformation anzeigen und beenden
```

**Comment by jorgebucaran** [comment] 2020-05-24 09:41
>@MaSven `fisher add jorgebucaran/fish-spark`

If that worked, could you clarify what _didn't_ work? I thought you couldn't install any packages at all?

**Comment by MaSven** [comment] 2020-05-24 14:43
I think I misread the first comment. But for me it is only happening with sdkman-for-fish.

**Comment by jorgebucaran** [comment] 2020-05-24 15:09
Thank you for clarifying that, @MaSven. When fisher installs a package, it'll also attempt to activate it, that means sourcing all the files inside functions, completions and conf.d directory.

Maybe there's something in [reitzig/sdkman-for-fish/blob/master/conf.d/sdk.fish](https://github.com/reitzig/sdkman-for-fish/blob/master/conf.d/sdk.fish) causing Fisher to fail.

Are you able to install reitzig/sdkman-for-fish by simply dropping {functions,conf.d}/sdk.fish inside your functions and conf.d directory respectively?

**Comment by MaSven** [comment] 2020-05-24 17:48
Am Sonntag, 24. Mai 2020, 17:09:18 CEST schrieb Jorge Bucaran:
> Thank you for clarifying that, @MaSven. When fisher installs a package, it'll also attempt to activate it, that means sourcing all the files inside functions, completions and conf.d directory.
> 
> Maybe there's something in [reitzig/sdkman-for-fish/blob/master/conf.d/sdk.fish](https://github.com/reitzig/sdkman-for-fish/blob/master/conf.d/sdk.fish) causing Fisher to fail.
> 
> Are you able to install reitzig/sdkman-for-fish by simply dropping {functions,conf.d}/sdk.fish inside your functions and conf.d directory respectively? 
> 
> 

Yes this works.

**Comment by jorgebucaran** [comment] 2020-05-24 18:21
Okay, I was anxious to install this package, but I decided to give it a go after checking the source again:

```console
fetching https://codeload.github.com/reitzig/sdkman-for-fish/tar.gz/master
linking ~/.config/fish/functions/sdk.fish
linking ~/.config/fish/completions/sdk.fish
linking ~/.config/fish/conf.d/sdk.fish
added 1 package in 0.17s
```

...and it installed without problems. I'm afraid that without a reliable way to reproduce this error, there's not much I can do.

**Closed by jorgebucaran** 2020-05-24 18:21 UTC

**Comment by reitzig** [comment] 2020-06-18 14:02
> So, repeat your steps, but instead of `reitzig/sdkman-for-fish@v1.3.0` try.
> 
> ```
> $ fisher add jorgebucaran/fish-spark
> ```
> 
> What happens?

One difference I note is that spark has only a single top-level file, while sdkman-for-fish has `completions`/`conf.d`/`functions`.
@tobia / @MaSven , can you reproduce with another package including multiple folders?

---

[This line](https://github.com/jorgebucaran/fisher/blob/017046abf3aef24c9fba61c2348b627136279975/fisher.fish#L308) seems fragile to me:

```fish
if command curl $curl_opts -Ss -w \"\" $url 2>&1 | command tar -xzf- -C $fisher_config/$pkg 2>/dev/null
```

We don't have pipefail (?) so it relies on `tar` exiting with an error whatever comes its way, if there's any issue.
Which it doesn't [always do](https://stackoverflow.com/q/10120702/539599), apparently.

So, @tobia  and @MaSven, what versions of `tar` do you fly? Can you check whether e.g.

```
command curl -Ss -w "" https://github.com/foo/bar | command tar -xzf- -C foo
echo $status
```

is?

@jorgebucaran , would it make sense to capture error output, and print it in case of an issue? I'll note that `curl` does not always return a failure status code, e.g. in case of a 404, unless flag `-f` is given but we never get an output here of a download failing.

What I _think_ might be going on here is the download fails for some reason, and an old version of tar exits with `0` despite not receiving tar-y input.

Then we enter the cp/mv orgy despite not having downloaded anything.

---

I will note that I do not understand [this sequence of commands](https://github.com/jorgebucaran/fisher/blob/017046abf3aef24c9fba61c2348b627136279975/fisher.fish#L309):

```fish
rm -Rf $fisher_cache/$pkg
mv -f $fisher_config/$pkg/* $fisher_cache/$pkg
```

If the glob matches exactly one file, this will work; otherwise, I read "copy A and B into C which doesn't exist".
Is it possible that the tarball sometimes containers more than that one folder you're expecting (maybe depending on user agent?), or some `tar` versions write something, or that old files are around there?

I tried to reproduce along these lines, but didn't manage to. :shrug:

**Comment by MaSven** [comment] 2020-07-12 13:29
I tried the same with https://github.com/rafaelrinaldi/pure and this seems to work normally. My tar version is 1.32 GNU. Maybe  i need an example with completions.

**Comment by jorgebucaran** [comment] 2020-07-12 14:25
Hey @MaSven @tobia @reitzig! So, is [this](https://github.com/jorgebucaran/fisher/issues/557#issue-518420718) solved or is it still happening?

**Comment by reitzig** [comment] 2020-07-27 07:33
@tobia will have to answer that; I've never been able to reproduce. :/

I'm happy to help and/or fix sdkman-for-fish -- if I get any hint as to what may be the problem.

**Comment by jorgebucaran** [comment] 2020-07-27 08:01
@reitzig No worries! People often wrong into issues where the culprit was not fisher, but something in their configuration or environment.
